apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-clinic-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-clinic-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: awesome-clinic-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: awesome-clinic-backend
        image: ashwilliams/awesome-clinic-backend:flask
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: RG-AKS-BlueTeam
  name: svc-awesome-clinic-backend
spec:
  type: LoadBalancer
  loadBalancerIP: 52.232.191.113
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: awesome-clinic-backend