on: [push]

# Environment variables available to all jobs and steps in this workflow
env:  
  CLUSTER_NAME: aks-cluster-demos
  CLUSTER_RESOURCE_GROUP: RG-AKS-BlueTeam
  NAMESPACE: demo
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    #Build and push to docker hub
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
        with:
          push: true
          tags: ashwilliams/awesome-clinic-backend:flask
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
   
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          AzureDeployment.yaml
